# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  services:
    # label used to access the service container
    # Use docker to run postgresql for testing
    # docker run --name myPostgresDb -p 5455:5432 -e POSTGRES_USER=postgresUser -e POSTGRES_PASSWORD=postgresPW -e POSTGRES_DB=postgresDB -d postgres
    postgres:
      # Docker Hub image
      image: postgres:latest
      # service environment variables
      # `POSTGRES_HOST` is `postgres`
      env:
        # optional (defaults to `postgres`)
        POSTGRES_DB: myPostgresDb
        # required
        POSTGRES_PASSWORD: postgresPW
        # optional (defaults to `5432`)
        POSTGRES_PORT: 5432
        # optional (defaults to `postgres`)
        POSTGRES_USER:  postgresUser
      ports:
        # maps tcp port 5432 on service container to the host
        - 5455:5432
      # set health checks to wait until postgres has started
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
      # Backend folder working directory.
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - name: Install PostgreSQL client
      run: |
            apt-get update
            apt-get install --yes postgresql-client
    - name: Query database
      run: psql -h postgres -d myPostgresDB -U postgresUser -c 'SELECT 1;'
      env:
          PGPASSWORD: postgresPW
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        build-root-directory: backend
        arguments: build

